#!/bin/bash -l
#SBATCH --account=uzh8
#SBATCH --job-name=nbody
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --hint=nomultithread
#SBATCH --output=output_nbody.log
#SBATCH --error=errors_nbody.log

module load cray
module load perftools-lite 

export OMP_NUM_THREADS=1

srun --cpu-bind=cores ./nbody

